FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY Desafio_Backend.sln ./

COPY API_Desafio_Backend/ API_Desafio_Backend/
COPY Library_Desafio_Backend/ Library_Desafio_Backend/

RUN dotnet restore Desafio_Backend.sln

RUN dotnet publish API_Desafio_Backend/API_Desafio_Backend.csproj -c Release -o /app/publish/api

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app/publish/api ./api

COPY --from=build /app/publish/web ./web

ENTRYPOINT ["dotnet", "api/Library_Desafio_Backend.dll"]